### PR TITLE
Update: Add lazy loading through data-url to side navigation plugin

### PR DESCRIPTION
**Pull request by pat270**
http://liferay.github.io/lexicon/content/sidenav/#side-navigation-data-api

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @pat270 

does it also show a loading indicator while the ajax call is sent?

thanks a ton for including this :+1:

**Comment by pat270** [comment]
@juliocamarero, there's no loading indicator, but maybe we can add a loading class or fire some events?

**Comment by juliocamarero** [comment]
Hey @pat270, it would be awesome if I could configure to the component a data-loading-class that is added to the panel while loading and removed on finishing. You would make me very happy if you add that :D

**Comment by juliocamarero** [comment]
Hey @natecavanaugh could you please prioritize this pull? Thanks a lot! :smile:

**Comment by natecavanaugh** [comment]
:+1: Merged and pushed to master. Thanks :)

View just my changes: https://github.com/liferay/lexicon/compare/pat270:54c584d3c2...49809ff6b2
View total diff: https://github.com/liferay/lexicon/compare/9ad8f69c1c...49809ff6b2

**Pull request closed without merging**
